In [69]:
import os
import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd
from tensorflow.keras.callbacks import TensorBoard

print("TensorFlow version: {}".format(tf.__version__))
print("Eager execution: {}".format(tf.executing_eagerly()))

TensorFlow version: 2.2.0
Eager execution: True


In [70]:
train_dataset_url = "https://storage.googleapis.com/download.tensorflow.org/data/iris_training.csv"
test_dataset_url = "https://storage.googleapis.com/download.tensorflow.org/data/iris_test.csv"

train_dataset_fp = tf.keras.utils.get_file(fname=os.path.basename(train_dataset_url),
                                           origin=train_dataset_url)
test_dataset_fp = tf.keras.utils.get_file(fname=os.path.basename(test_dataset_url),
                                          origin=test_dataset_url)

print("Local copy of the dataset file: {}".format(train_dataset_fp))

Local copy of the dataset file: C:\Users\LONAA32\.keras\datasets\iris_training.csv


In [92]:
def create_dataset(file_path, batch_size=1):

    dataset = tf.data.experimental.make_csv_dataset(file_path,
                                                    batch_size,
                                                    column_names=COLUMN_NAMES,
                                                    label_name=LABEL_NAME)
    return dataset

In [93]:
# column order in CSV file
COLUMN_NAMES = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
FEATURE_NAMES = COLUMN_NAMES[:-1]
LABEL_NAME = COLUMN_NAMES[-1]

print("Features: {}".format(FEATURE_NAMES))
print("Label: {}".format(LABEL_NAME))

Features: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
Label: species


In [94]:
BATCH_SIZE = 32

train_dataset = create_dataset(train_dataset_fp, batch_size=BATCH_SIZE)
test_dataset = create_dataset(test_dataset_fp, batch_size=BATCH_SIZE)

In [95]:
features, labels = next(iter(train_dataset))

print(features)

OrderedDict([('sepal_length', <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([6.6, 4.9, 6.4, 7.2, 5.6, 5.4, 4.9, 6.8, 5.3, 6.9, 6.7, 4.9, 4.6,
       7.3, 6.5, 4.9, 7.7, 5.8, 6.5, 7.2, 6.7, 6.1, 5.7, 4.4, 5.4, 4.8,
       7.7, 7.6, 5. , 5.7, 6.1, 6.6], dtype=float32)>), ('sepal_width', <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([3. , 3. , 3.1, 3. , 2.7, 3.4, 3.1, 3.2, 3.7, 3.2, 3.1, 2.5, 3.4,
       2.9, 3.2, 3.1, 3.8, 4. , 3. , 3.6, 3.3, 2.8, 2.8, 2.9, 3.9, 3.1,
       2.8, 3. , 3.5, 3. , 2.9, 2.9], dtype=float32)>), ('petal_length', <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([4.4, 1.4, 5.5, 5.8, 4.2, 1.5, 1.5, 5.9, 1.5, 5.7, 5.6, 4.5, 1.4,
       6.3, 5.1, 1.5, 6.7, 1.2, 5.5, 6.1, 5.7, 4. , 4.1, 1.4, 1.7, 1.6,
       6.7, 6.6, 1.6, 4.2, 4.7, 4.6], dtype=float32)>), ('petal_width', <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([1.4, 0.2, 1.8, 1.6, 1.3, 0.4, 0.1, 2.3, 0.2, 2.3, 2.4, 1.7, 0.3,
       1.8, 2. , 0.1, 2.2, 0.2, 1.8, 2.5, 2.1, 1.3, 1.3, 0.2,

In [96]:
for element in train_dataset.as_numpy_iterator():
    print(element)
    break

(OrderedDict([('sepal_length', array([5.7, 6.1, 6.8, 5.8, 6. , 6. , 5. , 6.4, 6.9, 6.3, 6.5, 4.6, 5.6,
       5.7, 6.5, 6.4, 4.9, 6.6, 6.1, 5.8, 6.9, 4.4, 6.5, 6.7, 6.7, 4.9,
       7.2, 6.2, 6.5, 4.9, 5.7, 7.2], dtype=float32)), ('sepal_width', array([3. , 2.9, 2.8, 2.6, 2.7, 2.9, 3.5, 2.8, 3.1, 3.3, 3. , 3.1, 2.5,
       2.8, 3. , 3.1, 3.1, 3. , 2.8, 2.7, 3.2, 3. , 3.2, 3.3, 3.1, 3.1,
       3.2, 2.2, 2.8, 3.1, 2.9, 3. ], dtype=float32)), ('petal_length', array([4.2, 4.7, 4.8, 4. , 5.1, 4.5, 1.3, 5.6, 4.9, 6. , 5.2, 1.5, 3.9,
       4.5, 5.5, 5.5, 1.5, 4.4, 4. , 5.1, 5.7, 1.3, 5.1, 5.7, 4.4, 1.5,
       6. , 4.5, 4.6, 1.5, 4.2, 5.8], dtype=float32)), ('petal_width', array([1.2, 1.4, 1.4, 1.2, 1.6, 1.5, 0.3, 2.2, 1.5, 2.5, 2. , 0.2, 1.1,
       1.3, 1.8, 1.8, 0.1, 1.4, 1.3, 1.9, 2.3, 0.2, 2. , 2.1, 1.4, 0.1,
       1.8, 1.5, 1.5, 0.1, 1.3, 1.6], dtype=float32))]), array([1, 1, 1, 1, 1, 1, 0, 2, 1, 2, 2, 0, 1, 1, 2, 2, 0, 1, 1, 2, 2, 0,
       2, 2, 1, 0, 2, 1, 1, 0, 1, 2]))


# FIRST WAY

In [97]:
def pack_features_vector(features, labels):
    """Pack the features into a single array."""
    features = tf.stack(list(features.values()), axis=1)
    return features, labels

In [98]:
train_dataset = train_dataset.map(pack_features_vector)

In [103]:
features, labels = next(iter(train_dataset))

print(features[:5])
print(labels)

tf.Tensor(
[[4.7 3.2 1.3 0.2]
 [5.1 3.7 1.5 0.4]
 [5.6 2.5 3.9 1.1]
 [6.1 2.8 4.  1.3]
 [5.7 3.  4.2 1.2]], shape=(5, 4), dtype=float32)
tf.Tensor([0 0 1 1 1 0 2 1 2 2 2 2 2 1 2 0 2 2 2 2 0 1 2 0 2 2 2 0 2 0 0 1], shape=(32,), dtype=int32)


In [104]:
# Build a keras DNN model using Sequential API
model = tf.keras.Sequential([
  tf.keras.layers.Dense(10, activation=tf.nn.relu, input_shape=(4,)),  # input shape required
  tf.keras.layers.Dense(10, activation=tf.nn.relu),
  tf.keras.layers.Dense(3, activation="softmax")  
])

In [105]:
predictions = model(features)
predictions[:5]

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0.18006371, 0.6033592 , 0.21657713],
       [0.17465869, 0.62154186, 0.20379946],
       [0.1298278 , 0.586272  , 0.28390017],
       [0.11674696, 0.60692537, 0.2763277 ],
       [0.12682088, 0.59196156, 0.28121752]], dtype=float32)>

In [107]:
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
# Compile the keras model
model.compile(optimizer="adam",
             loss=loss_object,
             metrics=["mse", "accuracy"])

In [108]:
history = model.fit(train_dataset,
                    steps_per_epoch=120,
                    epochs=50)

Epoch 1/50
120/120 [==============================] - 0s 1ms/step - loss: 0.9657 - mse: 1.1823 - accuracy: 0.5909
Epoch 2/50
120/120 [==============================] - 0s 921us/step - loss: 0.8147 - mse: 1.2449 - accuracy: 0.7031
Epoch 3/50
120/120 [==============================] - 0s 855us/step - loss: 0.7582 - mse: 1.2568 - accuracy: 0.8596
Epoch 4/50
120/120 [==============================] - 0s 899us/step - loss: 0.7005 - mse: 1.2753 - accuracy: 0.9646
Epoch 5/50
120/120 [==============================] - 0s 891us/step - loss: 0.6557 - mse: 1.2985 - accuracy: 0.9750
Epoch 6/50
120/120 [==============================] - 0s 875us/step - loss: 0.6285 - mse: 1.3162 - accuracy: 0.9766
Epoch 7/50
120/120 [==============================] - 0s 873us/step - loss: 0.6125 - mse: 1.3277 - accuracy: 0.9758
Epoch 8/50
120/120 [==============================] - 0s 887us/step - loss: 0.6026 - mse: 1.3352 - accuracy: 0.9760
Epoch 9/50
120/120 [==============================] - 0s 877us/step - loss

In [109]:
test_dataset = test_dataset.map(pack_features_vector)

In [110]:
test_dataset

<MapDataset shapes: ((32, 4), (32,)), types: (tf.float32, tf.int32)>

In [111]:
test_accuracy = tf.keras.metrics.Accuracy()

for (x, y) in test_dataset.take(50):
    # training=False is needed only if there are layers with different
    # behavior during training versus inference (e.g. Dropout).
    logits = model(x, training=False)
    prediction = tf.argmax(logits, axis=1, output_type=tf.int32)
    test_accuracy(prediction, y)

    
print("Test set accuracy: {:.3%}".format(test_accuracy.result()))

Test set accuracy: 93.313%


In [112]:
tf.stack([y,prediction],axis=1)

<tf.Tensor: shape=(32, 2), dtype=int32, numpy=
array([[0, 0],
       [1, 2],
       [1, 1],
       [0, 0],
       [0, 0],
       [2, 2],
       [1, 1],
       [2, 2],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [2, 2],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 2],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])>

In [113]:
BATCH_SIZE = 32

train_dataset = create_dataset(train_dataset_fp, batch_size=BATCH_SIZE)
test_dataset = create_dataset(test_dataset_fp, batch_size=BATCH_SIZE)

In [114]:
# Create input layer of feature columns
feature_columns = {header: tf.feature_column.numeric_column(header) for header in FEATURE_NAMES}

In [115]:
# Build a keras DNN model using Sequential API
model = tf.keras.Sequential([
  tf.keras.layers.DenseFeatures(feature_columns=feature_columns.values()),
  tf.keras.layers.Dense(10, activation=tf.nn.relu),  # input shape required
  tf.keras.layers.Dense(10, activation=tf.nn.relu),
  tf.keras.layers.Dense(3, activation="softmax")  
])

In [116]:
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
# Compile the keras model
model.compile(optimizer="adam",
             loss=loss_object,
             metrics=["mse", "accuracy"])

In [117]:
history = model.fit(train_dataset,
                    steps_per_epoch=120,
                    epochs=50)

Epoch 1/50
120/120 [==============================] - 0s 948us/step - loss: 0.9168 - mse: 1.2799 - accuracy: 0.6667
Epoch 2/50
120/120 [==============================] - 0s 893us/step - loss: 0.8460 - mse: 1.3235 - accuracy: 0.7000
Epoch 3/50
120/120 [==============================] - 0s 888us/step - loss: 0.8385 - mse: 1.3233 - accuracy: 0.7000
Epoch 4/50
120/120 [==============================] - 0s 879us/step - loss: 0.7006 - mse: 1.2886 - accuracy: 0.9193
Epoch 5/50
120/120 [==============================] - 0s 883us/step - loss: 0.6204 - mse: 1.3226 - accuracy: 0.9773
Epoch 6/50
120/120 [==============================] - 0s 874us/step - loss: 0.5997 - mse: 1.3374 - accuracy: 0.9823
Epoch 7/50
120/120 [==============================] - 0s 859us/step - loss: 0.5903 - mse: 1.3444 - accuracy: 0.9833
Epoch 8/50
120/120 [==============================] - 0s 858us/step - loss: 0.5848 - mse: 1.3485 - accuracy: 0.9833
Epoch 9/50
120/120 [==============================] - 0s 865us/step - lo

In [130]:
test_accuracy = tf.keras.metrics.Accuracy()

for (x, y) in test_dataset:
    # training=False is needed only if there are layers with different
    # behavior during training versus inference (e.g. Dropout).
    logits = model(x, training=False)
    prediction = tf.argmax(logits, axis=1, output_type=tf.int32)
    test_accuracy(prediction, y)
    break
    
print("Test set accuracy: {:.3%}".format(test_accuracy.result()))

Test set accuracy: 96.875%


In [131]:
tf.stack([y,prediction],axis=1)

<tf.Tensor: shape=(32, 2), dtype=int32, numpy=
array([[2, 2],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [2, 2],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [2, 2],
       [0, 0],
       [1, 2],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [2, 2],
       [0, 0],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1]])>